[project]
name = "vdab-job-seeker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.5",
    "feedgen>=1.0.0",
    "requests>=2.32.5",
    "xmltodict>=0.14.2",
    "yattag>=1.16.1",
]
