name: Generate VDAB feed

on:
  workflow_call:
  workflow_dispatch:

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    env:
      CONFIG_FILE: config/vdab.json
      OUTPUT_FILE: feeds/vdab.xml
      PAGE_COUNT: 20
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate RSS feed
        run: |
          python vdab.py -d -p $PAGE_COUNT -v $OUTPUT_FILE $CONFIG_FILE

      - name: Commit RSS feed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -f $OUTPUT_FILE
          git diff-index --quiet HEAD || git commit -m "Update VDAB RSS feed"
          git pull --rebase origin main
          git push
